function Guess(t,u){this.licenseId=t;this.playId=u;var k=new Hashtable,m=new Hashtable;k.put("3c3",["2c1"]);k.put("3c4",["3c1","2c1"]);m.put("3_2","3c3");m.put("3_23","3c4");k.put("4c4",["3c1"]);k.put("4c5",["4c1","3c1"]);k.put("4c6",["2c1"]);k.put("4c11",["4c1","3c1","2c1"]);m.put("4_3","4c4");m.put("4_34","4c5");m.put("4_2","4c6");m.put("4_234","4c11");k.put("5c5",["4c1"]);k.put("5c6",["5c1","4c1"]);k.put("5c10",["2c1"]);k.put("5c16",["5c1","4c1","3c1"]);k.put("5c20",["3c1","2c1"]);k.put("5c26",
["5c1","4c1","3c1","2c1"]);m.put("5_4","5c5");m.put("5_45","5c6");m.put("5_2","5c10");m.put("5_345","5c16");m.put("5_23","5c20");m.put("5_2345","5c26");k.put("6c6",["5c1"]);k.put("6c7",["6c1","5c1"]);k.put("6c15",["2c1"]);k.put("6c20",["3c1"]);k.put("6c22",["6c1","5c1","4c1"]);k.put("6c35",["3c1","2c1"]);k.put("6c42",["6c1","5c1","4c1","3c1"]);k.put("6c50",["4c1","3c1","2c1"]);k.put("6c57",["6c1","5c1","4c1","3c1","2c1"]);m.put("6_5","6c6");m.put("6_56","6c7");m.put("6_2","6c15");m.put("6_3","6c20");
m.put("6_456","6c22");m.put("6_23","6c35");m.put("6_3456","6c42");m.put("6_234","6c50");m.put("6_23456","6c57");k.put("7c7",["6c1"]);k.put("7c8",["7c1","6c1"]);k.put("7c21",["5c1"]);k.put("7c35",["4c1"]);k.put("7c120",["7c1","6c1","5c1","4c1","3c1","2c1"]);m.put("7_6","7c7");m.put("7_67","7c8");m.put("7_5","7c21");m.put("7_4","7c35");m.put("7_234567","7c120");k.put("8c8",["7c1"]);k.put("8c9",["8c1","7c1"]);k.put("8c28",["6c1"]);k.put("8c56",["5c1"]);k.put("8c70",["4c1"]);k.put("8c247",["8c1","7c1",
"6c1","5c1","4c1","3c1","2c1"]);m.put("8_7","8c8");m.put("8_78","8c9");m.put("8_6","8c28");m.put("8_5","8c56");m.put("8_4","8c70");m.put("8_2345678","8c247");var r=new Hashtable;r.put("2c1",["3c3","3c4","4c6","4c11","5c10","5c20","5c26","6c15","6c35","6c50","6c57","7c120","8c247"]);r.put("3c1",["3c4","4c4","4c5","4c11","5c16","5c20","5c26","6c20","6c35","6c42","6c50","6c57","7c120","8c247"]);r.put("4c1",["4c5","4c11","5c5","5c6","5c16","5c26","6c22","6c42","6c50","6c57","7c35","7c120","8c70","8c247"]);
r.put("5c1",["5c6","5c16","5c26","6c6","6c7","6c22","6c42","6c57","7c21","7c120","8c56","8c247"]);r.put("6c1",["6c7","6c22","6c42","6c57","7c7","7c8","7c120","8c28","8c247"]);r.put("7c1",["7c8","7c120","8c8","8c9","8c247"]);r.put("8c1",["8c9","8c247"]);var q=new CombAlgorithm;this.scheduleMap=new Hashtable;this.init=function(){if(this.licenseId==9)for(var b=0;b<schedules.length;b++){var e=new GuessFootballSchedule(schedules[b].id,schedules[b].leaguename,schedules[b].hostname,schedules[b].guestname,
schedules[b].overodds,schedules[b].starttime,schedules[b].stoptime,schedules[b].spfdgodds,schedules[b].spfggodds,schedules[b].rqspfdgodds,schedules[b].rqspfggodds,schedules[b].zjqdgodds,schedules[b].zjqggodds,schedules[b].bqcdgodds,schedules[b].bqcggodds,schedules[b].bfodds,schedules[b].dgrq,schedules[b].ggrq,schedules[b].schudlesno,schedules[b].bgcolor);this.scheduleMap.put(schedules[b].id,e)}else if(this.licenseId==10)for(b=0;b<schedules.length;b++){e=new GuessBasketballSchedule(schedules[b].id,
schedules[b].leaguename,schedules[b].hostname,schedules[b].guestname,schedules[b].overodds,schedules[b].starttime,schedules[b].stoptime,schedules[b].sfdgodds,schedules[b].sfggodds,schedules[b].rfsfdgodds,schedules[b].rfsfggodds,schedules[b].sfcodds,schedules[b].dxfdgodds,schedules[b].dxfggodds,schedules[b].dgrf,schedules[b].ggqf,schedules[b].dgyszf,schedules[b].ggyszf,schedules[b].bgcolor);this.scheduleMap.put(schedules[b].id,e)}};this.optimizePassType=function(b,e,c){var a=this.getMaxPassNum();if(this.playId==
6){var d=true,f=c.split("|");for(a=0;a<f.length;a++){for(var g=f[a].split(":")[1].split(",")[0].split("-")[0],h=f[a].split(":")[1].split(","),i=0;i<h.length;i++)if(h[i].split("-")[0]!=g){d=false;break}if(!d)break}if(d)a=this.getMixedMaxPassNum(c);else return e}if(b>a||b<2)return e;c=c.split("|");for(a=0;a<c.length;a++)if(c[a].split(":")[2]=="2")return e;f=e.split(",");e=[];c=[];d=[];for(a=0;a<f.length;a++)f[a].split("c")[1]=="1"?d.push(f[a].split("c")[0]):c.push(f[a]);d.length>0&&this.joinFreePt(b,
e,d);for(b=0;b<d.length;b++){f=false;for(a=0;a<e.length;a++)if(k.get(e[a]).toString().indexOf(d[b]+"c1")>-1){f=true;break}f||e.push(d[b]+"c1")}b="";for(a=0;a<e.length;a++)b+=e[a]+",";for(a=0;a<c.length;a++)b+=c[a]+",";return b=b.substring(0,b.length-1)};this.joinFreePt=function(b,e,c){for(var a=c.length;a>0;){for(var d=q.findComb(c,c.length,a),f=false,g=0;g<d.length;g++){for(var h="",i=0;i<d[g].length;i++)h+=d[g][i];if(m.get(b+"_"+h)!="undefined"){e.push(m.get(b+"_"+h));d=[];for(f=0;f<c.length;f++)h.indexOf(c[f])==
-1&&d.push(c[f]);this.joinFreePt(b,e,d);f=true;break}}if(f)break;a--}};this.getMixedMaxPassNum=function(b){var e=8;b=b.split("|");if(this.licenseId==9)for(var c=0;c<b.length;c++)for(var a=b[c].split(":")[1].split(","),d=0;d<a.length;d++){var f=parseInt(a[d].split("-")[0],10);switch(f){case 3:e=e>6?6:e;break;case 4:e=e>4?4:e;break;case 5:e=e>4?4:e}}else if(this.licenseId==10)for(c=0;c<b.length;c++){a=b[c].split(":")[1].split(",");for(d=0;d<a.length;d++){f=parseInt(a[d].split("-")[0],10);switch(f){case 3:e=
e>4?4:e}}}return e};this.getMaxPassNum=function(){var b=8;if(this.licenseId==9)switch(this.playId){case 1:b=8;break;case 2:b=8;break;case 3:b=6;break;case 4:b=4;break;case 5:b=4}else if(this.licenseId==10)switch(this.playId){case 1:b=8;break;case 2:b=8;break;case 3:b=4;break;case 4:b=8}return b};this.getStopTime=function(b){return this.scheduleMap.get(b).stopTime};this.getStartTime=function(b){return this.scheduleMap.get(b).startTime};this.getGgRqOrRf=function(b){var e=0;if(this.licenseId==9)e=this.scheduleMap.get(b).ggrq;
else if(this.licenseId==10)e=this.scheduleMap.get(b).ggrf+"`"+this.scheduleMap.get(b).ggyszf;return e};this.getPlayOdds=function(b,e){var c="0.0";if(this.licenseId==9)switch(e){case 1:c=this.scheduleMap.get(b).spfGgOdds;break;case 2:c=this.scheduleMap.get(b).rqspfGgOdds;break;case 3:c=this.scheduleMap.get(b).zjqGgOdds;break;case 4:c=this.scheduleMap.get(b).bqcGgOdds;break;case 5:c=this.scheduleMap.get(b).bfGgOdds}else if(this.licenseId==10)switch(e){case 1:c=this.scheduleMap.get(b).sfGgOdds;break;
case 2:c=this.scheduleMap.get(b).rfsfGgOdds;break;case 3:c=this.scheduleMap.get(b).sfcGgOdds;break;case 4:c=this.scheduleMap.get(b).dxfGgOdds}return c};this.getDgPlayOdds=function(b,e){var c="0.0";if(this.licenseId==9)switch(e){case 1:c=this.scheduleMap.get(b).spfDgOdds;break;case 2:c=this.scheduleMap.get(b).rqspfDgOdds;break;case 3:c=this.scheduleMap.get(b).zjqDgOdds;break;case 4:c=this.scheduleMap.get(b).bqcDgOdds;break;case 5:c=this.scheduleMap.get(b).bfGgOdds}else if(this.licenseId==10)switch(e){case 1:c=
this.scheduleMap.get(b).sfDgOdds;break;case 2:c=this.scheduleMap.get(b).rfsfDgOdds;break;case 3:c=this.scheduleMap.get(b).sfcGgOdds;break;case 4:c=this.scheduleMap.get(b).dxfDgOdds}return c};this.getOdds=function(b){var e="0.0";if(this.licenseId==9)switch(this.playId){case 1:e=this.scheduleMap.get(b).spfGgOdds;break;case 2:e=this.scheduleMap.get(b).rqspfGgOdds;break;case 3:e=this.scheduleMap.get(b).zjqGgOdds;break;case 4:e=this.scheduleMap.get(b).bqcGgOdds;break;case 5:e=this.scheduleMap.get(b).bfGgOdds}else if(this.licenseId==
10)switch(this.playId){case 1:e=this.scheduleMap.get(b).sfGgOdds;break;case 2:e=this.scheduleMap.get(b).rfsfGgOdds;break;case 3:e=this.scheduleMap.get(b).sfcGgOdds;break;case 4:e=this.scheduleMap.get(b).dxfGgOdds}return e};this.getBetOdds=function(b,e){var c="0.0",a=this.playId;if(this.playId==6){var d=e.split("-");a=parseInt(d[0]);e=d[1]}if(this.licenseId==9)switch(a){case 1:c=this.scheduleMap.get(b).getSpfGgBetOdd(e);break;case 2:c=this.scheduleMap.get(b).getRqspfGgBetOdd(e);break;case 3:c=this.scheduleMap.get(b).getZjqGgBetOdd(e);
break;case 4:c=this.scheduleMap.get(b).getBqcGgBetOdd(e);break;case 5:c=this.scheduleMap.get(b).getBfBetOdd(e)}else if(this.licenseId==10)switch(a){case 1:c=this.scheduleMap.get(b).getSfGgBetOdd(e);break;case 2:c=this.scheduleMap.get(b).getRfsfGgBetOdd(e);break;case 3:c=this.scheduleMap.get(b).getSfcGgBetOdd(e);break;case 4:c=this.scheduleMap.get(b).getDxfGgBetOdd(e)}return c};this.filteMutexs=function(b,e){for(var c=b.split("|"),a="",d=0;d<c.length;d++){var f=c[d].split(":");a+=f[0]+":";for(var g=
f[1].split(","),h=parseFloat(this.getBetOdds(f[0],g[0])),i=g[0],j=0;j<g.length;j++)if(e==1){if(parseFloat(this.getBetOdds(f[0],g[j]))>h){h=parseFloat(this.getBetOdds(f[0],g[j]));i=g[j]}}else if(parseFloat(this.getBetOdds(f[0],g[j]))<h){h=parseFloat(this.getBetOdds(f[0],g[j]));i=g[j]}h=this.getMutexMixedBets(f[0],i);for(j=0;j<g.length;j++){for(var l=false,n=0;n<h.length;n++)if(g[j]==h[n]&&g[j]!=i){l=true;break}l||(a+=g[j]+",")}a=a.substring(0,a.length-1)+":";a+=f[2]+"|"}return a=a.substring(0,a.length-
1)};this.getMutexMixedBets=function(b,e){var c=[],a=e.split("-");if(this.licenseId==9){var d=parseInt(a[0]),f=parseInt(this.getGgRqOrRf(b));switch(d){case 1:switch(a[1]){case "3":if(f>0){c.push("2-1");c.push("2-0")}else f==-1&&c.push("2-0");for(a=13;a<31;a++)c.push("5-"+a);c.push("4-31");c.push("4-30");c.push("4-11");c.push("4-10");c.push("4-01");c.push("4-00");break;case "1":if(f>0){c.push("2-1");c.push("2-0")}else{c.push("2-3");c.push("2-1")}for(a=0;a<13;a++)c.push("5-"+a);for(a=18;a<31;a++)c.push("5-"+
a);c.push("4-33");c.push("4-30");c.push("4-13");c.push("4-10");c.push("4-03");c.push("4-00");break;case "0":if(f>0)f==1&&c.push("2-3");else{c.push("2-3");c.push("2-1")}for(a=0;a<18;a++)c.push("5-"+a);c.push("4-33");c.push("4-31");c.push("4-13");c.push("4-11");c.push("4-03");c.push("4-01")}break;case 2:switch(a[1]){case "3":if(f>0){c.push("1-0");for(a=18;a<31;a++)c.push("5-"+a)}else{c.push("1-1");c.push("1-0");for(a=13;a<31;a++)c.push("5-"+a);c.push("4-31");c.push("4-11");c.push("4-01")}c.push("4-30");
c.push("4-10");c.push("4-00");break;case "1":if(f>0){c.push("1-3");c.push("1-1");for(a=0;a<18;a++)c.push("5-"+a);c.push("4-33");c.push("4-13");c.push("4-03");c.push("4-31");c.push("4-11");c.push("4-01")}else{c.push("1-1");c.push("1-0");for(a=13;a<31;a++)c.push("5-"+a);c.push("4-31");c.push("4-11");c.push("4-01");c.push("4-30");c.push("4-10");c.push("4-00")}break;case "0":if(f>0){c.push("1-3");c.push("1-1");for(a=0;a<18;a++)c.push("5-"+a);c.push("4-33");c.push("4-13");c.push("4-03");c.push("4-31");
c.push("4-11");c.push("4-01")}else{c.push("1-1");c.push("1-0");for(a=13;a<31;a++)c.push("5-"+a);c.push("4-31");c.push("4-11");c.push("4-01");c.push("4-30");c.push("4-10");c.push("4-00")}}break;case 5:a=parseInt(a[1]);if(a<13){c.push("1-1");c.push("1-0");if(f>0){c.push("2-1");c.push("2-0")}c.push("4-31");c.push("4-11");c.push("4-01");c.push("4-30");c.push("4-10");c.push("4-00")}else if(a<18){c.push("1-3");c.push("1-0");if(f>0){c.push("2-1");c.push("2-0")}else{c.push("2-3");c.push("2-1")}c.push("4-33");
c.push("4-30");c.push("4-13");c.push("4-10");c.push("4-03");c.push("4-00")}else{c.push("1-3");c.push("1-1");if(!(f>0)){c.push("2-3");c.push("2-1")}c.push("4-33");c.push("4-31");c.push("4-13");c.push("4-11");c.push("4-03");c.push("4-01")}break;case 4:if(a[1]=="33"||a[1]=="13"||a[1]=="03"){c.push("1-1");c.push("1-0");if(f>0){c.push("2-1");c.push("2-0")}for(a=13;a<31;a++)c.push("5-"+a)}else if(a[1]=="33"||a[1]=="13"||a[1]=="03"){c.push("1-3");c.push("1-0");if(f>0){c.push("2-1");c.push("2-0")}else{c.push("2-3");
c.push("2-1")}for(a=0;a<13;a++)c.push("5-"+a);for(a=18;a<31;a++)c.push("5-"+a)}else{c.push("1-3");c.push("1-1");if(!(f>0)){c.push("2-3");c.push("2-1")}for(a=0;a<18;a++)c.push("5-"+a)}}}else if(this.licenseId==10){d=parseInt(a[0]);f=parseFloat(this.getGgRqOrRf(b));switch(d){case 1:if(a[0]=="3"){f>0&&c.push("2-0");for(a=0;a<6;a++)c.push("3-"+a)}else{f>0||c.push("2-3");for(a=6;a<12;a++)c.push("3-"+a)}break;case 2:if(a[0]=="3"){if(!(f>0)){c.push("2-0");for(a=0;a<6;a++)c.push("3-"+a)}}else if(f>0){c.push("2-3");
for(a=6;a<12;a++)c.push("3-"+a)}break;case 3:if(parseInt(a[1])>5){c.push("1-0");f>0&&c.push("2-0")}else{c.push("1-3");f>0||c.push("2-3")}}}return c};this.calcFreePassNum=function(b,e){var c=0,a=parseInt(e.split("c")[0]);a=q.findComb(b,b.length,a);for(var d=0;d<a.length;d++){for(var f=1,g=0;g<a[d].length;g++)f*=a[d][g].length;c+=f}return c};this.calcCombPassNum=function(b,e){var c=0,a=parseInt(e.split("c")[0]);if(a==b.length){a=k.get(e);for(var d=0;d<a.length;d++)c+=this.calcFreePassNum(b,a[d])}else{var f=
q.findComb(b,b.length,a);a=k.get(e);for(d=0;d<f.length;d++)for(var g=0;g<a.length;g++)c+=this.calcFreePassNum(f[d],a[g])}return c};this.calcBetNum0=function(b,e){for(var c=0,a=0;a<e.length;a++)c+=parseInt(e[a].split("c")[1])>1?this.calcCombPassNum(b,e[a]):this.calcFreePassNum(b,e[a]);return c};this.calcDgBetNum=function(b){b=b.split("|");for(var e=0,c=0;c<b.length;c++)e+=b[c].split(":")[1].split(",").length;return e};this.calcBetNum=function(b,e){if(e=="1c1")return this.calcDgBetNum(b);var c=[],a=
[],d=b.split("|"),f=e.split(","),g=0;if(this.playId!=6){for(var h=0;h<d.length;h++){for(var i=[],j=d[h].split(":")[1].split(","),l=0;l<j.length;l++)i.push(j[l]);d[h].split(":")[2]=="2"?a.push(i):c.push(i)}if(a.length==0)for(h=0;h<f.length;h++)g+=parseInt(f[h].split("c")[1])>1?this.calcCombPassNum(c,f[h]):this.calcFreePassNum(c,f[h]);else{d=[];for(h=0;h<f.length;h++)d.push(f[h]);g=this.calcDanTuoBetNum(a,c,d)}}else{for(h=0;h<d.length;h++){i=[];g=[];j=d[h].split(":")[1].split(",");var n=j[0].split("-")[0];
for(l=0;l<j.length;l++){if(n!=j[l].split("-")[0]){for(var o=[],p=0;p<g.length;p++)o.push(g[p]);i.push(o);n=j[l].split("-")[0];g=[]}g.push(j[l]);if(l==j.length-1){o=[];for(p=0;p<g.length;p++)o.push(g[p]);i.push(o)}}d[h].split(":")[2]=="2"?a.push(i):c.push(i)}d=[];for(h=0;h<f.length;h++)d.push(f[h]);g=a.length==0?this.calcMixedBetNum(c,d):this.calcMixedDanTuoBetNum(a,c,d)}return g};this.calcDanTuoBetNum=function(b,e,c){for(var a=0,d=0;d<c.length;d++){var f=parseInt(c[d].split("c")[0]);f=q.findComb(e,
e.length,f-b.length);for(var g=0;g<f.length;g++){for(var h=1,i=0;i<f[g].length;i++)h*=f[g][i].length;for(i=0;i<b.length;i++)h*=b[i].length;a+=h}}return a};this.calcFreePassBonus=function(b,e,c){var a=0;e=parseInt(e.split("c")[0]);b=q.findComb(b,b.length,e);for(e=0;e<b.length;e++){for(var d=1,f=0;f<b[e].length;f++)d*=parseFloat(b[e][f]);a+=d}return(new Number(a*2*c)).toFixed(2)};this.calcCombPassBonus=function(b,e,c){var a=0,d=parseInt(e.split("c")[0]);if(d==b.length){e=k.get(e);for(d=0;d<e.length;d++)a+=
parseFloat(this.calcFreePassBonus(b,e[d],c))}else{b=q.findComb(b,b.length,d);e=k.get(e);for(d=0;d<b.length;d++)for(var f=0;f<e.length;f++)a+=parseFloat(this.calcFreePassBonus(b[d],e[f],c))}return(new Number(a)).toFixed(2)};this.compare=function(b,e){return parseFloat(b)<parseFloat(e)?1:parseFloat(b)>parseFloat(e)?-1:0};this.compareASC=function(b,e){return parseFloat(b)>parseFloat(e)?1:parseFloat(b)<parseFloat(e)?-1:0};this.calcBonus0=function(b,e,c){for(var a=[],d=0;d<b.length;d++){b[d].sort(this.compare);
a.push(b[d][0])}for(d=b=0;d<e.length;d++)b+=parseInt(e[d].split("c")[1])>1?parseFloat(this.calcCombPassBonus(a,e[d],c)):parseFloat(this.calcFreePassBonus(a,e[d],c));return(new Number(b)).toFixed(2)};this.calcDgMinBonus=function(b,e){for(var c=b.split("|"),a=[],d=0;d<c.length;d++){this.toSingleCode(c[d].split(":")[1]);var f=c[d].split(":")[1].split(","),g=0;g=parseFloat(this.getBetOdds(c[d].split(":")[0],f[0]));for(var h=0;h<f.length;h++)if(parseFloat(this.getBetOdds(c[d].split(":")[0],f[h]))<g)g=
parseFloat(this.getBetOdds(c[d].split(":")[0],f[h]));a.push(g)}a.sort(this.compareASC);return(new Number(a[0]*e*2)).toFixed(2)};this.calcMinBonus=function(b,e,c){if(e=="1c1")return this.calcDgMinBonus(b,c);var a=e.split(",");e=8;for(var d=0;d<a.length;d++)if(a[d].split("c")[1]!="1"){var f=k.get(a[d]);if(parseInt(f[f.length-1].split("c")[0],10)<e)e=parseInt(f[f.length-1].split("c")[0],10)}else if(parseInt(a[d].split("c")[0],10)<e)e=parseInt(a[d].split("c")[0],10);a=b.split("|");b=[];for(d=0;d<a.length;d++){this.toSingleCode(a[d].split(":")[1]);
f=a[d].split(":")[1].split(",");var g=0;g=parseFloat(this.getBetOdds(a[d].split(":")[0],f[0]));for(var h=0;h<f.length;h++)if(parseFloat(this.getBetOdds(a[d].split(":")[0],f[h]))<g)g=parseFloat(this.getBetOdds(a[d].split(":")[0],f[h]));b.push(g)}a=1;b.sort(this.compareASC);for(d=0;d<e;d++)a*=b[d];return(new Number(a*c*2)).toFixed(2)};this.calcDgBonus=function(b,e){var c=0;if(this.playId==6)for(var a=b.split("|"),d=0;d<a.length;d++)for(var f=this.toSingleCode(a[d].split(":")[1]),g=0;g<f.length;g++){var h=
0,i=f[g].split(",");h=parseFloat(this.getBetOdds(a[d].split(":")[0],i[0]));for(var j=0;j<i.length;j++)if(parseFloat(this.getBetOdds(a[d].split(":")[0],i[j]))>h)h=parseFloat(this.getBetOdds(a[d].split(":")[0],i[j]));c+=h}return(new Number(c*e*2)).toFixed(2)};this.calcBonus=function(b,e,c){if(e=="1c1")return this.calcDgBonus(b,c);if(this.playId==6)b=this.filteMutexs(b,1);b=b.split("|");var a=e.split(",");e=[];for(var d=0;d<a.length;d++)e.push(a[d]);a=[];var f=[];if(this.playId!=6){for(d=0;d<b.length;d++){for(var g=
b[d].split(":"),h=g[1].split(","),i=[],j=0;j<h.length;j++)i.push(this.getBetOdds(g[0],h[j]));g[2]=="2"?f.push(i):a.push(i)}b=0;b=f.length==0?this.calcBonus0(a,e,c):this.calcDanTuoBonus(f,a,e,c)}else{for(d=0;d<b.length;d++){h=[];i=[];g=b[d].split(":")[1].split(",");var l=g[0].split("-")[0];for(j=0;j<g.length;j++){if(l!=g[j].split("-")[0]){for(var n=[],o=0;o<i.length;o++)n.push(i[o]);h.push(n);l=g[j].split("-")[0];i=[]}i.push(this.getBetOdds(b[d].split(":")[0],g[j]));if(j==g.length-1){n=[];for(o=0;o<
i.length;o++)n.push(i[o]);h.push(n)}}b[d].split(":")[2]=="2"?f.push(h):a.push(h)}b=f.length==0?this.calcMixedMaxBonus(a,e,c):this.calcMixedDanTuoMaxBonus(f,a,e,c)}return b};this.calcDanTuoBonus=function(b,e,c,a){for(var d=0,f=[],g=0;g<b.length;g++){b[g].sort(this.compare);f.push(b[g][0])}b=[];for(g=0;g<e.length;g++){e[g].sort(this.compare);b.push(e[g][0])}for(g=0;g<c.length;g++){e=parseInt(c[g].split("c")[0]);e=q.findComb(b,b.length,e-f.length);for(var h=0;h<e.length;h++){for(var i=1,j=0;j<e[h].length;j++)i*=
parseFloat(e[h][j]);for(j=0;j<f.length;j++)i*=parseFloat(f[j]);d+=i}}return(new Number(d*2*a)).toFixed(2)};this.calcMixedBetNum=function(b,e){for(var c=0,a=0;a<e.length;a++){var d=parseInt(e[a].split("c")[0]);d=q.findComb(b,b.length,d);for(var f=0;f<d.length;f++)for(var g=q.findNmComb(d[f]),h=0;h<g.length;h++)c+=parseInt(e[a].split("c")[1])>1?this.calcCombPassNum(g[h],e[a]):this.calcFreePassNum(g[h],e[a])}return c};this.calcMixedDanTuoBetNum=function(b,e,c){for(var a=0,d=q.findNmComb(b),f=0;f<c.length;f++){var g=
parseInt(c[f].split("c")[0]);g=q.findComb(e,e.length,g-b.length);for(var h=0;h<g.length;h++)for(var i=q.findNmComb(g[h]),j=0;j<i.length;j++){for(var l=1,n=0;n<i[j].length;n++)l*=i[j][n].length;for(n=0;n<d.length;n++){for(var o=l,p=0;p<d[n].length;p++)o*=d[n][p].length;a+=o}}}return a};this.calcMixedMaxBonus=function(b,e,c){for(var a=0,d=0;d<e.length;d++){var f=parseInt(e[d].split("c")[0]);f=q.findComb(b,b.length,f);for(var g=0;g<f.length;g++)for(var h=q.findNmComb(f[g]),i=0;i<h.length;i++){for(var j=
[],l=0;l<h[i].length;l++){h[i][l].sort(this.compare);j.push(h[i][l][0])}a+=parseInt(e[d].split("c")[1])>1?parseFloat(this.calcCombPassBonus(j,e[d],c)):parseFloat(this.calcFreePassBonus(j,e[d],c))}}return(new Number(a)).toFixed(2)};this.calcMixedDanTuoMaxBonus=function(b,e,c,a){for(var d=0,f=q.findNmComb(b),g=0;g<c.length;g++){var h=parseInt(c[g].split("c")[0]);h=q.findComb(e,e.length,h-b.length);for(var i=0;i<h.length;i++)for(var j=q.findNmComb(h[i]),l=0;l<j.length;l++){for(var n=[],o=0;o<j[l].length;o++){j[l][o].sort(this.compare);
n.push(j[l][o][0])}o=1;for(var p=0;p<n.length;p++)o*=parseFloat(n[p]);for(p=0;p<f.length;p++){n=o;for(var s=0;s<f[p].length;s++){f[p][s].sort(this.compare);n*=parseFloat(f[p][s][0])}d+=n}}}return(new Number(d*2*a)).toFixed(2)};this.tsfCmp2Sngl=function(b,e){for(var c=b.split("|"),a=[],d=0;d<c.length;d++){for(var f=[],g=c[d].split(":"),h=g[1].split(","),i=0;i<h.length;i++)f.push(g[0]+":"+h[i]+":0");a.push(f)}c=[];f=e.split(",");for(d=0;d<f.length;d++){i=parseInt(f[d].split("c")[0]);g=q.findComb(a,
a.length,i);for(i=0;i<g.length;i++){h=q.findNmComb(g[i]);for(var j=0;j<h.length;j++){for(var l="",n=0;n<h[j].length;n++)l+=h[j][n]+"|";l=l.substring(0,l.length-1);c.push(l)}}}return c};this.toSingleCode=function(b){var e=[],c="";b=b.split(",");for(var a=0;a<b.length;a++){var d=b[a];if(c=="")c=d+",";else if(parseInt(c.split(",")[0].split("-")[0])==parseInt(d.split("-")[0]))c+=d+",";else{c=c.substring(0,c.length-1);e.push(c);c=d+","}if(a==b.length-1){c=c.substring(0,c.length-1);e.push(c)}}return e};
this.splitHhCode=function(b){var e=[];b=b.split("|");for(var c=b[0].split(":"),a=this.toSingleCode(c[1]),d=0;d<a.length;d++)this.findSubHhNmComb(e,c[0]+":"+a[d]+":"+c[2]+"|",b,b.length-1);return e};this.findSubHhNmComb=function(b,e,c,a){if(a==0)b.push(e.substring(0,e.length-1));else for(var d=c[c.length-a].split(":"),f=this.toSingleCode(d[1]),g=0;g<f.length;g++){var h=e;h+=d[0]+":"+f[g]+":"+d[2]+"|";this.findSubHhNmComb(b,h,c,a-1)}};this.createOptList=function(b,e){for(var c=this.tsfCmp2Sngl(b,e),
a=[],d=0;d<c.length;d++){for(var f=new Optimization,g=c[d].split("|"),h=1,i=0;i<g.length;i++){var j=g[i].split(":");h*=parseFloat(this.getBetOdds(j[0],j[1]))}h=parseFloat((new Number(h*2)).toFixed(2));f.baseBonus=h;f.betCode=c[d];f.multiple=1;a.push(f)}return a};this.averOptimize=function(b,e){if(e<=b.length*2)return b;for(var c=0,a=0;a<b.length;a++)if(b[a].baseBonus>c)c=b[a].baseBonus;var d=100;if(parseInt(e)>=1E4)d=1E3;else if(parseInt(e)>=1E5)d=1E4;else if(parseInt(e)>=1E6)d=1E5;var f=[];for(a=
0;a<b.length;a++)f[a]=Math.round(c/b[a].baseBonus*d);for(a=d=0;a<f.length;a++)d+=f[a];c=parseFloat(parseInt(e)/(d*2));for(a=d=0;a<b.length;a++){b[a].multiple=Math.round(c*f[a]);d+=b[a].multiple}f=parseInt(e)/2;if(f>d)for(;f>d;){c=parseFloat(b[0].baseBonus*b[0].multiple);for(a=0;a<b.length;a++){var g=parseFloat(b[a].baseBonus*b[a].multiple);if(g<c)c=g}for(a=0;a<b.length;a++){g=parseFloat(b[a].baseBonus*b[a].multiple);if(g==c){b[a].multiple+=1;d++}}}else if(f<d)for(;f<d;){c=parseFloat(b[0].baseBonus*
b[0].multiple);for(a=0;a<b.length;a++){g=parseFloat(b[a].baseBonus*b[a].multiple);if(g>c)c=g}for(a=0;a<b.length;a++){g=parseFloat(b[a].baseBonus*b[a].multiple);if(g==c){b[a].multiple-=1;d--}}}return b};this.hotOptimize=function(b,e){if(e<=b.length*2)return b;for(var c=0,a=0;a<b.length;a++){var d=parseFloat(b[a].baseBonus);if(d<e){d=parseInt(e/d)+1;c+=d;b[a].multiple=d}else{c++;b[a].multiple=1}}var f=parseFloat(b[0].baseBonus);for(a=0;a<b.length;a++){d=parseFloat(b[a].baseBonus);if(d<f)f=d}for(a=0;a<
b.length;a++){d=parseFloat(b[a].baseBonus);if(d==f){c=parseInt(e)/2-c;b[a].multiple+=c;break}}return b};this.coldOptimize=function(b,e){if(e<=b.length*2)return b;for(var c=0,a=0;a<b.length;a++){var d=parseFloat(b[a].baseBonus);if(d<e){d=parseInt(e/d)+1;c+=d;b[a].multiple=d}else{c++;b[a].multiple=1}}var f=parseFloat(b[0].baseBonus);for(a=0;a<b.length;a++){d=parseFloat(b[a].baseBonus);if(d>f)f=d}for(a=0;a<b.length;a++){d=parseFloat(b[a].baseBonus);if(d==f){c=parseInt(e)/2-c;b[a].multiple+=c;break}}return b};
this.evenOptimize=function(b,e){if(e<=b.length*2)return b;for(var c=0,a=0;a<b.length;a++)if(b[a].even==1){var d=parseFloat(b[a].baseBonus);if(d<e){d=parseInt(e/d)+1;c+=d;b[a].multiple=d}}var f=e-c*2,g=0;for(a=0;a<b.length;a++)if(parseFloat(b[a].baseBonus)>g&&b[a].even==1)g=parseFloat(b[a].baseBonus);var h=[],i=100;if(parseInt(e)>=1E4)i=1E3;else if(parseInt(e)>=1E5)i=1E4;else if(parseInt(e)>=1E6)i=1E5;for(a=0;a<b.length;a++)if(b[a].even!=1){d=parseFloat(b[a].baseBonus);h[a]=Math.round(g/d*i)}else h[a]=
0;for(a=d=0;a<h.length;a++)d+=h[a];d=parseFloat(parseInt(f)/(d*2));for(a=0;a<b.length;a++)if(b[a].even!=1){c+=Math.round(d*h[a]);b[a].multiple=Math.round(d*h[a])}h=parseInt(e)/2;if(h>c)for(;h>c;){g=parseFloat(b[0].baseBonus*b[0].multiple);for(a=0;a<b.length;a++){d=parseFloat(b[a].baseBonus*b[a].multiple);if(d<g)g=d}for(a=0;a<b.length;a++){d=parseFloat(b[a].baseBonus*b[a].multiple);if(d==g){b[a].multiple+=1;c++}}}else if(h<c)for(;h<c;){g=parseFloat(b[0].baseBonus*b[0].multiple);for(a=0;a<b.length;a++){d=
parseFloat(b[a].baseBonus*b[a].multiple);if(d>g)g=d}for(a=0;a<b.length;a++){d=parseFloat(b[a].baseBonus*b[a].multiple);if(d==g){b[a].multiple-=1;c--}}}return b}}function Optimization(t,u,k){this.betCode=t;this.baseBonus=u;this.multiple=k;this.even=0};
